config/routes.rb
Rails.application.routes.draw do
  get 'groups/new'

  root "users#index"

  get 'join/:id' => 'groups#join'
  get 'leave/:id' => 'groups#leave'
  get 'delete/:id' => 'groups#delete'
  get 'login' => 'sessions#new', as: 'new_login'
  post 'login' => 'sessions#create', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  resources :users
  resources :groups
end

app/models/group.rb
class Group < ActiveRecord::Base
	validates :name,  presence: true, length: { in: 6..30 }
	validates :description, presence: true, length: { in: 11..60 }
	
	belongs_to :user
	belongs_to :admin, :class_name => "User", :foreign_key => :admin_id

	has_many :joins
	has_many :users, through: :joins

end

app/models/join.rb
class Join < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :joins
  has_many :groups, through: :joins
  
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  before_save :downcase

  validates :first_name, :last_name, presence: true, length: { in: 2..20 }
  validates :password, :password_confirmation, length: { in: 8..18 }
  validates :email, presence: true, format: { with:EMAIL_REGEX }

  private
  	def downcase
  		self.email.downcase!
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||=User.find_by(id: session[:user_id]) if session.key? 'user_id'
  end
  helper_method :current_user

  def require_login
  	redirect_to new_login_path unless session.key? 'user_id'
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	skip_before_action :require_login, except:[:destroy]

  def index
  	@groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @admin = group.user
    if @group.users.include? current_user 
      render "/groups/show"
    else
      render "/groups/other"
    end
  end

  def other
    @group = Group.find(params[:id])
    @admin = group.user
    render "/groups/other"
  end

  def delete
  	# delete group
    @group = Group.find(params[:id])
    @group.users.delete
    @group.delete
    redirect_to "/groups"
  end

  def join
  	# join a group
    @group = Group.find(params[:id])
    @group.users << current_user
    redirect_to "/groups"
  end

  def leave
  	# leave a group
    @group = Group.find(params[:id])
    @group.users.destroy(current_user)
    redirect_to "/groups"
  end

  def create
  	# create a group
  	@group = Group.create(name: params[:name], description: params[:description], member_count: 1, admin_id: current_user.id)
    if @group.valid?
      # @group.association(current_user)
      # @group.admin_id = current_user.id
      @group.users << current_user
      redirect_to :back
    else
      flash[:alert] = @group.errors.full_messages
      redirect_to :back
    end
  end

  private
  helper_method def group
  	@group ||=Group.find_by_id(params[:id])
  end
    helper_method def admin
    @admin ||=User.find_by_id(params[:id])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, except:[:destroy]

  def new
  end

  def create
  	@user = User.find_by(email: params[:email])
  	errors = []

  	if @user
  		if @user.authenticate(params[:password])
  			session[:user_id] = @user.id
  			return redirect_to groups_path
  		else
  			errors << 'Invalid password'
  		end
  	else
  		errors << 'Email does not exist in records. Please register first.'
  	end

  	redirect_to :back, alert: errors
  	# scrap this?
  end

  def destroy
  	session.delete :user_id if session.key? 'user_id'
  	redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :require_login, only: [:new, :create]
	def index
	end

	

	def create
		if new_user.valid?
			session[:user_id] = new_user.id
	  
			return redirect_to groups_path
		end
		redirect_to :back, alert: new_user.errors.full_messages

	end
	private
	  	# memoization
	  helper_method def user
	  		@user ||=User.find(params[:id])
	  end

	  helper_method def new_user
	  	@new_user ||=User.create(user_params)
	  end

	  def user_params
	  	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<div class="container-fluid bg-2 text-center">
	<h2>Hello, <%= current_user.first_name.capitalize %>!</h2>
		<button class="btn"><a class="btn" href="<%= logout_path %>" data_method="delete">Logout</a></button>
	<div class="row">
		<div class="col-sm-6">
			<h3>Here are the organizations you may join:</h3>

			<% @groups.each do |group| %>
			<h3><a href="/groups/<%= group.id %>"><%= group.name %></a></h3>
				<% if group.admin_id == current_user.id %>
					<button class="btn"><a class="btn" href="/delete/<%= group.id %>">Delete</a></button>
				<% end %>
			<p>Members: <%= group.users.count %></p>
			<!-- counts number of users associated with Users foreign key -->
			<p><% group.description %></p>
			<% end %>
		</div>

		<form class="form-horizontal col-sm-6" action="/groups" method="post">
			<h3>Create a new organization:</h3>
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<div class="form-group">
				<label class="control-label col-sm-2" for="name">Group Name:</label>
				<div class="col-sm-10">
				<input type="text" class="form-control" name="name" placeholder="ex. Just Peel It">
				</div>
			</div>
			<div class="form-group">
				<label class="control-label col-sm-2" for="description">Description:</label>
				<div class="col-sm-10">
				<input type="text" class="form-control" name="description" placeholder="Banana Society Meetings">
				</div>
			</div>
			<div class="form-group">
				<button class="btn" type="submit">Create</button>
			</div>
			<div class="form-group">
				<%= render 'partials/errors' %>
			</div>
		</form>

</div>

app/views/groups/other.html.erb
<div class="container-fluid bg-2 text-center">
	<h3><%= group.name %></h3>
	<button class="btn"><a class="btn" href="/join/<%= group.id %>">Join Group</a></button>
	
	<h4><%= group.description %></h4>

	<h3>Created by: <%= group.admin.first_name %> <%= group.admin.last_name %></h3>

		<h3>Members:</h3>
	<% group.users.each do |x|  %>
		<p><%= x.first_name %> <%= x.last_name %></p>
	<% end %>
	<button class="btn"><a class="btn" href="<%= groups_path %>">Dashboard</a></button>
	<button class="btn"><a class="btn" href="/logout" data_method="delete">Logout</a></button>
</div>

app/views/groups/show.html.erb
<div class="container-fluid bg-2 text-center">
	<h3><%= group.name %></h3>
	<button class="btn"><a class="btn" href="/leave/<%= group.id %>">Leave Group</a></button>
	
	<h4><%= group.description %></h4>

	<h3>Created by: <%= group.admin.first_name %> <%= group.admin.last_name %></h3>

		<h3>Members:</h3>
	<% group.users.each do |x|  %>
		<p><%= x.first_name %> <%= x.last_name %></p>
	<% end %>
	<button class="btn"><a class="btn" href="<%= groups_path %>">Dashboard</a></button>
	<button class="btn"><a class="btn" href="/logout" data_method="delete">Logout</a></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Belt3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="styles.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/partials/_errors.html.erb
<% if flash[:alert] %>
  <% flash[:alert].each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

app/views/users/index.html.erb
<div class="container-fluid text-center">
	<div class="row">
		<form class="col-sm-6" action="<%= users_path %>" method="post">
			<!-- this uses the route path given by default restful routes in RoR -->
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<h1>New Here? Register!</h1>
			<div class='form-group'>
				<label class="control-label" for="first_name">First Name</label>
				<input type="text" class="form-control" placeholder="First Name" name="user[first_name]">
			</div>
			<div class='form-group'>
				<label class="control-label" for="last_name">Last Name</label>
				<input type="text" class="form-control" placeholder="Last Name" name="user[last_name]">
			</div>
			<div class='form-group'>
				<label class="control-label" for="email">Email</label>
				<input type="text" class="form-control" placeholder="Email" name="user[email]">
			</div>
			<div class='form-group'>
				<label for="password">Password</label>
				<input type="password" class="form-control" placeholder="Password" name="user[password]">
			</div>
			<div class='form-group'>
				<label>Confirm Password</label>
				<input type="password" class="form-control" placeholder="Password" name="user[password_confirmation]">
			</div>
			<div class='form-group'>
				<button class="btn btn-default" type="submit" value="register">Sign Up</button>
			</div>
		</form>
		<div class="col-sm-6">
			<%= render 'partials/errors' %>
		</div>
	</div>	
</div>